# NOTE: Uncomment next line with `org` property to deploy this project
#       to serverless.com dashboard
#org: prorokxp
app: prisma-aws-lambda-example
service: prisma-aws-lambda-example
plugins:
  # - serverless-rollup-plugin
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-esbuild

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

functions:
  graphql:
    handler: dist/server.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

# only include the Prisma binary required on AWS Lambda while packaging
package:
  exclude:
    - node_modules/**
  # patterns:
  #   - '!node_modules/prisma-client/node_modules/.prisma/client/libquery_engine-*'
  #   - 'node_modules/prisma-client/node_modules/.prisma/client/libquery_engine-rhel-*'
  #   - '!node_modules/prisma-client/node_modules/prisma/libquery_engine-*'
  #   - '!node_modules/prisma-client/node_modules/@prisma/engines/**'

custom:
  serverless-offline:
    useChildProcesses: true
  rollup:
    config: ./rollup.config.js
