# NOTE: Uncomment next line with `org` property to deploy this project
#       to serverless.com dashboard
#org: prorokxp
app: prisma-aws-lambda-example
service: prisma-aws-lambda-example
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  # Use Webpack for final packaging
  # - serverless-bundle

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x

functions:
  graphql:
    handler: dist/server.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

# only include the Prisma binary required on AWS Lambda while packaging
package:
  individually: true
  patterns:
    - "!.*/**"
    - "!**"
    - "dist/**"

custom:
  serverless-offline:
    useChildProcesses: true
